version: '2'
services:
  mysql:
    image: dockerhub.geetools.net:5000/geecommerce/demo-mysql:latest
    container_name: gc_demo_mysql
    ports:
    - 3306:3306
    restart: always
  mongo:
    image: dockerhub.geetools.net:5000/geecommerce/demo-mongodb:latest
    container_name: gc_demo_mongodb
    ports:
    - 27017:27017
    restart: always
  tomcat:
    image: dockerhub.geetools.net:5000/geecommerce/tomcat8-java8:latest
    container_name: gc_demo_tomcat
    command: /bin/bash -c "envsubst '$${TOMCAT_HTTP_PORT},$${TOMCAT_REDIRECT_PORT},$${TOMCAT_SHUTDOWN_PORT}' < /usr/local/tomcat/conf/server.template > /usr/local/tomcat/conf/server.xml && /entrypoint.sh"
    environment:
      - GC_HOME=/usr/local/geecommerce-local
      - TOMCAT_HTTP_PORT=8585
      - TOMCAT_REDIRECT_PORT=8443
      - TOMCAT_SHUTDOWN_PORT=8005
    ports:
    - 8585:8585
    - 8000:8000
    depends_on:
    - mysql
    - mongo
    - elasticsearch
    links:
    - mysql
    - mongo
    - elasticsearch
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"    
  nginx:
    image: dockerhub.geetools.net:5000/geecommerce/demo-nginx:latest
    container_name: gc_demo_nginx
    command: /bin/bash -c "envsubst '$${NGINX_PORT},$${TOMCAT_PORT}' < /etc/nginx/conf.d/geecommerce_proxy.template > /etc/nginx/conf.d/geecommerce_proxy.conf && nginx -g 'daemon off;'"
    environment:
      - NGINX_PORT=85
      - TOMCAT_PORT=8585
    ports:
    - 85:85
    - 443:443
    depends_on:
    - tomcat
    links:
    - tomcat
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  elasticsearch:
    image: elasticsearch:1.7.6
    container_name: gc_demo_es
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdemodata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    restart: always
  jobsdaemon:
    image: dockerhub.geetools.net:5000/geecommerce/jobs-daemon:latest
    container_name: gc_demo_jobs_daemon
    environment:
      - GC_HOME=/usr/local/geecommerce
    ports:
    - 1099:1099
    depends_on:
    - mysql
    - mongo
    - elasticsearch
    - tomcat
    links:
    - mysql
    - mongo
    - elasticsearch
  quartzdesk:
    image: dockerhub.geetools.net:5000/geecommerce/demo-quartzdesk:1.0
    container_name: gc_demo_quartzdesk
    ports:
    - 8090:8080
    depends_on:
    - mysql
    - jobsdaemon
    links:
    - mysql
    - jobsdaemon
volumes:
  esdemodata:
    driver: local
